exclude:
  - /Harshit_Vashisth
  - Code_With_Harry/basics
  - Code_With_Harry/intermediate
  - Code_With_Harry/web_scrapping_example
  - Coursera_JS_Specialization/Course-1--Basics/lessons
  - Coursera_JS_Specialization/Course-2--Animation-with-JS-&-jQuery/lessons
  - README
